version: '3.7'

services:
    mongodb:
        image: mongo:latest
        environment:
            MONGO_INITDB_DATABASE: "$SCIST_DB_NAME"
            MONGO_INITDB_ROOT_USERNAME: "$SCIST_DB_USER"
            MONGO_INITDB_ROOT_PASSWORD: "$SCIST_DB_PASSWORD" 
        ports:
            - "${SCIST_DB_PORT}:27017"
        volumes:
            - MongoData:/data/db

volumes:
    MongoData:
